# Generated by Django 6.0.1 on 2026-08-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_gatewaypaymentsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatewaypaymentsession',
            name='purpose',
            field=models.CharField(choices=[('consultation_booking', 'Consultation booking'), ('followup_booking', 'Follow-up booking'), ('lab_order', 'Lab order'), ('lab_token', 'Lab token bulk')], max_length=30),
        ),
    ]
